version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development

