version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - DB_URI_TEST=${DB_URI_TEST}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

